// <auto-generated />
using System;
using ForumApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumApp.Infrastructure.Migrations
{
    [DbContext(typeof(ForumAppDbContext))]
    [Migration("20230601200758_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForumApp.Infrastructure.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Guid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Content");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Title");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28fb4356-8a4f-4c7b-82e6-427d1dbc3dd3"),
                            Content = "Enter the enchanting realm of World of Warcraft, where you embark on an epic journey through a meticulously crafted fantasy world. With boundless possibilities and a rich tapestry of lore, WoW immerses you in a vibrant universe teeming with diverse races, captivating landscapes, and legendary creatures.Choose from an array of distinct classes and professions, each offering unique abilities and playstyles, as you carve your path to greatness. Whether you prefer the stalwart might of a warrior, the arcane mastery of a mage, the cunning precision of a rogue, or the mystical healing powers of a priest, the choices are endless.Venture forth into vast continents, from the hauntingly beautiful forests of Teldrassil to the scorching deserts of Tanaris, and unravel a gripping narrative woven through countless quests and encounters. Engage in thrilling dungeons, challenging raids, and intense PvP battles that test your mettle and reward you with valuable loot.",
                            Title = "World of Warcraft"
                        },
                        new
                        {
                            Id = new Guid("10dd04d8-999a-4e8a-87e0-f166a2606dbf"),
                            Content = "League of Legends is a team-based multiplayer online battle arena (MOBA) game. Choose unique champions, fight on diverse battlefields, and strategize with teammates to destroy the enemy Nexus. With a wide roster of champions, intense combat, and regular updates, LoL offers endless hours of strategic fun and competitive gameplay.",
                            Title = "League of Legends"
                        },
                        new
                        {
                            Id = new Guid("70e120e4-4c40-45bb-baed-dc0227e2d64e"),
                            Content = "Northgard is a captivating strategy game that transports players to a mythical Viking world. With its immersive gameplay and beautiful aesthetics, it offers a fresh take on the genre. Settling new lands, managing resources, and expanding your Viking clan's influence make for a compelling experience. The game strikes a balance between accessible mechanics and deep strategic depth, allowing both casual players and seasoned strategists to enjoy it. The evolving seasons and challenging events keep you on your toes, forcing you to adapt your strategies and overcome obstacles. The attention to detail in the visuals and sound design adds to the game's atmosphere, creating an engaging and immersive environment. Whether you prefer peaceful exploration or aggressive conquest, Northgard offers multiple paths to victory, providing replayability and keeping you engaged. The multiplayer mode allows you to compete or cooperate with friends, adding a social element to the experience. While the game could benefit from additional content and more variety in victory conditions, Northgard remains a solid and enjoyable strategy game that deserves a place in any gamer's library.",
                            Title = "Northgard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
